import type { GitIdentity } from "./types.js";

function q(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\"/g, '\\"');
}

export type RenderGitconfigOptions = {
  identity?: GitIdentity;
  enableGithubSshRewrite: boolean;
  safeDirectory?: string | string[];
};

export function renderGitconfig(options: RenderGitconfigOptions): string {
  const lines: string[] = [
    "# Generated by pi-ez-chat-git. Do not edit; changes are overwritten when the VM starts.",
    "",
  ];
  if (options.identity) {
    lines.push("[user]", `\tname = ${options.identity.name}`, `\temail = ${options.identity.email}`, "");
  }
  if (options.enableGithubSshRewrite) {
    lines.push('[url "ssh://git@github.com/"]', "\tinsteadOf = https://github.com/", "");
  }
  const safe = options.safeDirectory ?? "*";
  const safeDirs = Array.isArray(safe) ? safe : [safe];
  if (safeDirs.length > 0) {
    lines.push("[safe]");
    for (const dir of safeDirs) lines.push(`\tdirectory = ${q(dir)}`);
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}
